<?php include 'inside/header.php' ?>




<section class="inner_Section" style="background-image: url('./assets/img/inner_banner/placement.jpg');">


    <div class="container">
        <h1 class="title ">
            Fees <br class="d-md-block d-none">Payment
        </h1>
    </div>
</section>

<section class="feespayemts">
    <div class="container">
        <div class="feespayemts-box">

            <h2 class="title">TERMS AND <span>CONDITIONS</span></h2>
            <p>Please follow the instructions carefully:</p>

            <ul>
                <li>Once you select the "PAY NOW" option, you will be redirected to the payment gateway.</li>
                <li>Please select your option of payment and complete the transaction.</li>
                <li>Payment process normally takes a few seconds. If your internet connectivity is slow you will receive a
                    PAYMENT CONFIRMATION SLIP after successful transaction. Please save the slip for future reference.</li>
                <li>If the payment is NOT SUCCESSFUL due to any reason, the status of the payment failure will be displayed
                    on the screen.</li>
                <li>In case one of the above happens, there is heavy delay in any response from the system – if you have not
                    proceeded with payment and get an error, try again after logging out.</li>
                <li>In case you have given all the details and clicked on confirm, but do not get any response, please check
                    with your bank.</li>
                <li>Every transaction has a unique reference number generated by our Payment SUCCESSFUL confirmation.</li>
                <li>In case the payment is not successful, please do not try to make the payment and get PAYMENT SUCCESSFUL
                    confirmation.</li>
                <li>If you have any doubts please contact the accounts department.</li>
                <li>Please make a note of Reference/Transaction Details in case of Net banking or Card payment.</li>
            </ul>

            <hr>

            <h4>Cancellation / Refund Policy</h4>
            <p>There is NO CANCELLATION option if the end users once payment is made.</p>
            <p>Students/Parents can approach the Accounts Department for refund with proof of transaction reference / your
                bank statement.</p>

            <p class="important">
                <strong>IMPORTANT NOTE:</strong> By submitting a payment through the online payment gateway, you are
                agreeing to these terms and conditions and related instructions.
            </p>

            <p class="mode">
                <strong>Mode of Payments:</strong> NET BANKING / DEBIT CARD / CREDIT CARD / WALLET
            </p>

            <a href="https://razorpay.com/us/?utm_source=google&utm_medium=cpc&utm_campaign=RPSME-RPPerf-GSearchBrand-Prospect-Dweb-Core&utm_adgroup=brandsearch_core_exact&utm_content=RPSME-Brand-010223&utm_term=razorpay&utm_gclid=Cj0KCQiA7rDMBhCjARIsAGDBuEAqtBaFA4Pk4wqidzwUX6TU_2HQJQnvr_bheN2AczSeFcCzvixr5vMaApbNEALw_wcB&utm_campaignID=400139470&utm_adgroupID=27293859910&utm_adID=689518700854&utm_network=g&utm_device=c&utm_matchtype=e&utm_devicemodel=&utm_adposition=&utm_location=9061840&gad_source=1&gad_campaignid=400139470&gbraid=0AAAAADdXWPodHdcXUPboaG6rw3K7we2MW&gclid=Cj0KCQiA7rDMBhCjARIsAGDBuEAqtBaFA4Pk4wqidzwUX6TU_2HQJQnvr_bheN2AczSeFcCzvixr5vMaApbNEALw_wcB" class="btn-animated btn-light mt-4 ">
                <div class="btn-text-wrap">
                    <div class="btn-text">Pay Now</div>
                    <div class="btn-text-hover">Pay Now</div>
                </div>
                <div class="btn-icon-wrap">
                    <img src="https://cdn.prod.website-files.com/68e0f069e7077842f6665fd3/68e254fc5b4fb72c7d7f2407_icon-white-arrow-up.svg"
                        alt="Arrow" class="btn-icon">
                    <img src="https://cdn.prod.website-files.com/68e0f069e7077842f6665fd3/68e254fc5b4fb72c7d7f2407_icon-white-arrow-up.svg"
                        alt="Arrow" class="btn-icon-hover">
                </div>
            </a>

        </div>

        <div class="loan-banner">
            <h3>Need Loan? We Have You Covered!</h3>
            <p>Avail Instant Loan With Our Partners</p>

            <div class="ban-btn d-flex justify-content-center text-center mt-3">

                <a href="#" class="btn-animated btn-light ">
                    <div class="btn-text-wrap">
                        <div class="btn-text">Apply to Join</div>
                        <div class="btn-text-hover">Apply to Join</div>
                    </div>
                    <div class="btn-icon-wrap">
                        <img src="https://cdn.prod.website-files.com/68e0f069e7077842f6665fd3/68e254fc5b4fb72c7d7f2407_icon-white-arrow-up.svg"
                            alt="Arrow" class="btn-icon">
                        <img src="https://cdn.prod.website-files.com/68e0f069e7077842f6665fd3/68e254fc5b4fb72c7d7f2407_icon-white-arrow-up.svg"
                            alt="Arrow" class="btn-icon-hover">
                    </div>
                </a>




            </div>
        </div>
    </div>
</section>





<?php include 'inside/footer.php' ?>